// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgZzSA5VMIY9SNV2255QS1y9HEV8pSkzg',
    appId: '1:389512526917:web:77470305a514e99368772c',
    messagingSenderId: '389512526917',
    projectId: 'jiraapp-46b2d',
    authDomain: 'jiraapp-46b2d.firebaseapp.com',
    storageBucket: 'jiraapp-46b2d.firebasestorage.app',
    measurementId: 'G-E641BYMG22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6p2A2Q0sXpmAayxJByQncgZB4DGwUUr0',
    appId: '1:389512526917:android:831f46e64248b23068772c',
    messagingSenderId: '389512526917',
    projectId: 'jiraapp-46b2d',
    storageBucket: 'jiraapp-46b2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgVP_xFavAqkPYD9nzqTGKZBwPBAa3IX8',
    appId: '1:389512526917:ios:73a97bff2115bd4068772c',
    messagingSenderId: '389512526917',
    projectId: 'jiraapp-46b2d',
    storageBucket: 'jiraapp-46b2d.firebasestorage.app',
    iosBundleId: 'com.example.jira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgVP_xFavAqkPYD9nzqTGKZBwPBAa3IX8',
    appId: '1:389512526917:ios:73a97bff2115bd4068772c',
    messagingSenderId: '389512526917',
    projectId: 'jiraapp-46b2d',
    storageBucket: 'jiraapp-46b2d.firebasestorage.app',
    iosBundleId: 'com.example.jira',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgZzSA5VMIY9SNV2255QS1y9HEV8pSkzg',
    appId: '1:389512526917:web:75bbfbdd3f36e97568772c',
    messagingSenderId: '389512526917',
    projectId: 'jiraapp-46b2d',
    authDomain: 'jiraapp-46b2d.firebaseapp.com',
    storageBucket: 'jiraapp-46b2d.firebasestorage.app',
    measurementId: 'G-00FWF3DDB4',
  );

}